In [11]:
from pathlib import Path
import pandas as pd

path = Path("../data/raw/ema_demand/20251027.xls")

path.exists(), path.stat().st_size

(True, 61440)

In [12]:
raw = pd.read_excel(path, header=None)

raw.head(20)

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Date,2025-10-27 00:00:00,NaN,NaN,2025-10-28 00:00:00,NaN,NaN,2025-10-29 00:00:00,NaN,NaN,...,NaN,2025-10-31 00:00:00,NaN,NaN,2025-11-01 00:00:00,NaN,NaN,2025-11-02 00:00:00,NaN,NaN
2,Period Ending Time,Mon,NaN,NaN,Tue,NaN,NaN,Wed,NaN,NaN,...,NaN,Fri,NaN,NaN,Sat,NaN,NaN,Sun,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,System Demand (Actual),NEM Demand (Actual),NEM Demand (Forecast),System Demand (Actual),NEM Demand (Actual),NEM Demand (Forecast),System Demand (Actual),NEM Demand (Actual),NEM Demand (Forecast),...,NEM Demand (Forecast),System Demand (Actual),NEM Demand (Actual),NEM Demand (Forecast),System Demand (Actual),NEM Demand (Actual),NEM Demand (Forecast),System Demand (Actual),NEM Demand (Actual),NEM Demand (Forecast)
5,00:30,6613.229622,6471.9,6445.5,6520.731098,6379.5,6384,6865.070219,6722.9,6701.7,...,6818.4,7055.466864,6919.7,6932.5,7049.541447,6911.1,6688.5,7071.095199,6929.7,6822.2
6,01:00,6486.341388,6348.4,6316.9,6395.819402,6254.4,6251.2,6702.116624,6559.3,6554.1,...,6677,6899.589138,6762,6793,6903.429139,6764.3,6574.9,6924.638993,6782.1,6765
7,01:30,6385.410645,6243,6211.2,6294.718619,6151.1,6136.5,6589.283222,6444.2,6409,...,6455.8,6772.759703,6634.4,6585.8,6778.040394,6636.7,6539.5,6810.813618,6667.6,6564.7
8,02:00,6321.837062,6182.3,6127.5,6210.979637,6070.2,6066.7,6482.360157,6340.5,6317.3,...,6362.2,6682.569069,6545.4,6485.1,6671.508745,6529.3,6439.7,6715.615821,6575.9,6466.3
9,02:30,6258.047356,6116.6,6064.1,6138.905725,5995.4,6003.6,6410.201928,6266.5,6243.9,...,6286.6,6602.832718,6464.7,6396.1,6581.9191,6440.5,6355.6,6632.26646,6492.1,6391.3
10,03:00,6205.892086,6066.4,6017.1,6078.533547,5936.4,5942.3,6364.661725,6220,6167.4,...,6222.3,6531.427502,6392.9,6345.5,6505.370662,6363.8,6273.2,6557.389483,6417.6,6323.1
11,03:30,6176.630854,6036.3,5957.8,6032.311947,5890.8,5896.6,6326.62735,6183,6122.3,...,6173.2,6462.632035,6324,6300.6,6445.219954,6305.2,6211.3,6489.853697,6348.2,6265.8
12,04:00,6126.59312,5984.4,5932.7,6003.861459,5863.1,5862,6286.775863,6142.6,6088.9,...,6124.6,6421.618967,6282.7,6255.4,6405.266507,6265.1,6171.6,6437.734579,6298.7,6219.2
13,04:30,6034.924178,5892.5,5944.9,5997.946319,5856.2,5828.2,6257.025601,6113.8,6058.3,...,6069,6411.553327,6275.5,6219.1,6380.038239,6240.1,6151.5,6408.036934,6266.6,6188.2
14,05:00,5969.453389,5827.5,5941.7,6018.05652,5875.9,5824.9,6254.704393,6111.1,6047.3,...,6054.7,6409.962284,6272.2,6219.8,6362.478219,6220.7,6138.3,6393.334757,6252.9,6172.8
15,05:30,6018.491017,5875.6,5942.5,6082.501239,5942.1,5903.3,6319.221184,6175,6114.4,...,6126.8,6454.753581,6318.6,6292.1,6392.726155,6249.7,6165.4,6404.642127,6262.3,6184.7
16,06:00,6122.138131,5978.7,6013.8,6198.49293,6056.6,6040.7,6432.169799,6286.6,6232.9,...,6249.9,6552.033459,6413.6,6400.4,6431.265374,6289.2,6201.4,6429.088324,6286.6,6225.9
17,06:30,6347.675652,6202.5,6223.5,6415.177367,6269.6,6261.4,6640.51464,6498.6,6453.2,...,6466.7,6748.504083,6606.7,6604.3,6525.559711,6386.2,6301.1,6501.913011,6359.2,6310.1
18,07:00,6538.82055,6397,6380.7,6598.037413,6459.2,6443.2,6808.756125,6669.5,6638.8,...,6651.5,6899.962619,6763.3,6769,6594.567622,6453.5,6372,6555.452609,6412.7,6353.5
19,07:30,6789.251501,6643.5,6576.8,6790.194332,6646.7,6647.3,7030.265629,6885.5,6844.3,...,6861.9,7077.835552,6934.5,6951,6682.642488,6539.5,6456,6587.703471,6444.4,6381.6

In [5]:
raw.tail(20)

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
39,17:30,7647.695965,7502.6,7457.1,7877.434142,7736.3,7649,7857.66901,7721.5,7664.3,...,7767.5,8087.466387,7947.8,7923.4,7483.350438,7345,7258.4,7105.402196,6961.1,7029.2
40,18:00,7604.794085,7459.3,7441,7850.301735,7707.4,7635.9,7844.792909,7707.1,7636.1,...,7738.1,7975.749805,7836.2,7942.1,7461.867063,7331,7278.2,7085.792976,6942.7,7015.4
41,18:30,7519.38438,7377.8,7400.2,7768.697064,7629.8,7570.8,7734.721109,7602,7561.1,...,7651.9,7856.986316,7717.1,7765.5,7459.020298,7328.7,7273.9,7099.464723,6958.1,7001.5
42,19:00,7534.444803,7394.2,7419.8,7799.453586,7657.7,7598.8,7768.953474,7635.5,7596.1,...,7688.3,7871.792457,7731.9,7735.5,7523.939131,7389.3,7320.9,7204.887416,7061,7049.3
43,19:30,7501.667535,7363.2,7391.4,7796.890579,7655,7578.9,7753.557905,7617.3,7553.9,...,7655.5,7845.134873,7711.1,7695.2,7563.374551,7428.9,7360.9,7268.75716,7126.8,7105.3
44,20:00,7484.26365,7342.4,7369.4,7804.991037,7660.1,7559.6,7755.508481,7618.2,7541.5,...,7640.4,7848.582697,7710.9,7681,7601.770767,7465.7,7375.3,7306.62245,7164.7,7147.1
45,20:30,7465.265841,7323.4,7343.4,7798.777986,7660.2,7555,7766.834929,7627.5,7530.6,...,7638.9,7852.364017,7715.2,7675,7632.581422,7495.2,7391,7324.080747,7183.2,7182.6
46,21:00,7439.872308,7296.6,7304,7790.473528,7649.1,7538,7760.148969,7617.6,7520,...,7630.4,7849.082759,7710.4,7660.7,7644.646701,7509.3,7417.9,7350.910647,7212.9,7210.9
47,21:30,7373.080408,7233,7236.9,7741.950537,7603.9,7484.2,7726.358328,7589.8,7477.4,...,7560.1,7807.658812,7668.2,7618.7,7643.800014,7509.8,7405.5,7342.93752,7207.7,7175.9
48,22:00,7272.792728,7128.5,7124.2,7655.571657,7508.1,7386.5,7650.21795,7504,7380.7,...,7472.7,7730.926494,7587.3,7565.6,7613.990506,7478.3,7355.7,7289.454108,7150.9,7115.5
49,22:30,7100.038126,6959.6,6954.8,7482.077657,7339.6,7214.9,7483.105888,7342.6,7207,...,7302.6,7577.027051,7436.6,7396.8,7511.443462,7375.2,7243.2,7159.45715,7023.2,7033.6
50,23:00,6955.915777,6810.5,6804.4,7345.884677,7199.2,7060.6,7341.716076,7204.2,7037.7,...,7133.6,7475.317662,7333.1,7199,7429.496225,7292.4,7162.8,7044.731401,6905.8,6931.8
51,23:30,6800.740813,6657,6653,7189.046333,7045.1,6919.2,7194.220574,7054.7,6906.4,...,7017.6,7347.157905,7204.2,6954.7,7322.263991,7184.2,7065,6916.952743,6778.2,6781.4
52,00:00,6674.163511,6532.4,6524.6,7037.896565,6891.9,6808.9,7061.043823,6921.5,6811.6,...,6926.7,7215.231484,7074.3,6868.1,7216.126115,7075.6,6843.9,6802.122052,6662.7,6719.1
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Note:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,1. System Demand (Actual): includes demand of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,2. NEM Demand (Actual): Actual Demand met by a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,3. NEM Demand (Forecast): Forecast demand for ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,4. All units in MW.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
raw.dtypes

0        str
1     object
2     object
3     object
4     object
5     object
6     object
7     object
8     object
9     object
10    object
11    object
12    object
13    object
14    object
15    object
16    object
17    object
18    object
19    object
20    object
21    object
dtype: object

In [7]:
raw.shape, raw.iloc[:10, :5]

((59, 22),
                                                    0                        1  \
 0                                                ...                      NaN
 1                                               Date      2025-10-27 00:00:00
 2                                 Period Ending Time                      Mon
 3                                                NaN                      NaN
 4                                                NaN   System Demand (Actual)
 5                                              00:30              6613.229622
 6                                              01:00              6486.341388
 7                                              01:30              6385.410645
 8                                              02:00              6321.837062
 9                                              02:30              6258.047356

                       2                       3                        4
 0                   NaN                     NaN                      NaN
 1                   NaN                     NaN      2025-10-28 00:00:00
 2                   NaN                     NaN                      Tue
 3                   NaN                     NaN                      NaN
 4   NEM Demand (Actual)   NEM Demand (Forecast)   System Demand (Actual)
 5                6471.9                  6445.5              6520.731098
 6                6348.4                  6316.9              6395.819402
 7                  6243                  6211.2              6294.718619
 8                6182.3                  6127.5              6210.979637
 9                6116.6                  6064.1              6138.905725  )

In [8]:
raw.iloc[:, :7]

,0,1,2,3,4,5,6
0,...,NaN,NaN,NaN,NaN,NaN,NaN
1,Date,2025-10-27 00:00:00,NaN,NaN,2025-10-28 00:00:00,NaN,NaN
2,Period Ending Time,Mon,NaN,NaN,Tue,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,System Demand (Actual),NEM Demand (Actual),NEM Demand (Forecast),System Demand (Actual),NEM Demand (Actual),NEM Demand (Forecast)
5,00:30,6613.229622,6471.9,6445.5,6520.731098,6379.5,6384
6,01:00,6486.341388,6348.4,6316.9,6395.819402,6254.4,6251.2
7,01:30,6385.410645,6243,6211.2,6294.718619,6151.1,6136.5
8,02:00,6321.837062,6182.3,6127.5,6210.979637,6070.2,6066.7
9,02:30,6258.047356,6116.6,6064.1,6138.905725,5995.4,6003.6
10,03:00,6205.892086,6066.4,6017.1,6078.533547,5936.4,5942.3
11,03:30,6176.630854,6036.3,5957.8,6032.311947,5890.8,5896.6
12,04:00,6126.59312,5984.4,5932.7,6003.861459,5863.1,5862
13,04:30,6034.924178,5892.5,5944.9,5997.946319,5856.2,5828.2
14,05:00,5969.453389,5827.5,5941.7,6018.05652,5875.9,5824.9
15,05:30,6018.491017,5875.6,5942.5,6082.501239,5942.1,5903.3
16,06:00,6122.138131,5978.7,6013.8,6198.49293,6056.6,6040.7
17,06:30,6347.675652,6202.5,6223.5,6415.177367,6269.6,6261.4
18,07:00,6538.82055,6397,6380.7,6598.037413,6459.2,6443.2
19,07:30,6789.251501,6643.5,6576.8,6790.194332,6646.7,6647.3
20,08:00,6988.229357,6845,6784.6,6986.160144,6847.8,6849.3
21,08:30,7258.967286,7114.8,7065.6,7242.102472,7101.4,7087.4
22,09:00,7384.178009,7241.9,7213.9,7423.544804,7284.9,7230.1
23,09:30,7505.011678,7364.2,7362.1,7534.261482,7393.1,7361
24,10:00,7578.096433,7440.3,7395.8,7579.566651,7443.7,7437
25,10:30,7705.555767,7561.2,7441.2,7678.823399,7534.8,7482.5
26,11:00,7753.904425,7615.9,7470.7,7671.349798,7531.6,7506.9
27,11:30,7732.985602,7588.1,7566.1,7735.548498,7590.8,7563.8
28,12:00,7652.436392,7509.7,7572.4,7636.011366,7493.7,7504.5
29,12:30,7561.627489,7417.7,7493.4,7629.428455,7489.6,7475.7
30,13:00,7554.860455,7416.3,7435.9,7645.917495,7505.6,7427.9
31,13:30,7605.358029,7462.9,7441.3,7719.015254,7576.9,7473.5
32,14:00,7604.291081,7460.7,7478,7760.545385,7620,7533.8
33,14:30,7585.198403,7443.4,7498.9,7784.267791,7642.2,7600.2
34,15:00,7556.922177,7414.8,7490.6,7768.263296,7624.8,7620
35,15:30,7542.956696,7400.4,7467.7,7743.35198,7604,7612
36,16:00,7531.594738,7387.8,7448.1,7790.4451,7647.9,7611.7
37,16:30,7579.021808,7436.2,7452.7,7829.397209,7687.8,7636
38,17:00,7613.979537,7469.6,7456.6,7852.031986,7715.1,7655.7
39,17:30,7647.695965,7502.6,7457.1,7877.434142,7736.3,7649
40,18:00,7604.794085,7459.3,7441,7850.301735,7707.4,7635.9
41,18:30,7519.38438,7377.8,7400.2,7768.697064,7629.8,7570.8
42,19:00,7534.444803,7394.2,7419.8,7799.453586,7657.7,7598.8
43,19:30,7501.667535,7363.2,7391.4,7796.890579,7655,7578.9
44,20:00,7484.26365,7342.4,7369.4,7804.991037,7660.1,7559.6
45,20:30,7465.265841,7323.4,7343.4,7798.777986,7660.2,7555
46,21:00,7439.872308,7296.6,7304,7790.473528,7649.1,7538
47,21:30,7373.080408,7233,7236.9,7741.950537,7603.9,7484.2
48,22:00,7272.792728,7128.5,7124.2,7655.571657,7508.1,7386.5
49,22:30,7100.038126,6959.6,6954.8,7482.077657,7339.6,7214.9
50,23:00,6955.915777,6810.5,6804.4,7345.884677,7199.2,7060.6
51,23:30,6800.740813,6657,6653,7189.046333,7045.1,6919.2
52,00:00,6674.163511,6532.4,6524.6,7037.896565,6891.9,6808.9
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Note:,NaN,NaN,NaN,NaN,NaN,NaN
55,1. System Demand (Actual): includes demand of ...,NaN,NaN,NaN,NaN,NaN,NaN
56,2. NEM Demand (Actual): Actual Demand met by a...,NaN,NaN,NaN,NaN,NaN,NaN
57,3. NEM Demand (Forecast): Forecast demand for ...,NaN,NaN,NaN,NaN,NaN,NaN
58,4. All units in MW.,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
monday = raw.iloc[5:53, 0:4].copy()

monday.columns = [
    "Period Ending Time",
    *raw.iloc[4, 1:4].tolist(),
]

date = pd.Timestamp(raw.iloc[1, 1]).normalize()

period_ending = monday.pop("Period Ending Time").astype(str)

timestamp = pd.to_datetime(
    date.strftime("%Y-%m-%d") + " " + period_ending,
    format="%Y-%m-%d %H:%M",
    errors="raise",
)

timestamp.loc[period_ending.eq("00:00")] += pd.Timedelta(days=1)

monday.insert(
    0,
    "Timestamp",
    timestamp.dt.tz_localize("Asia/Singapore"),
)

monday = monday.reset_index(drop=True)

monday

,Timestamp,System Demand (Actual),NEM Demand (Actual),NEM Demand (Forecast)
0,2025-10-27 00:30:00+08:00,6613.229622,6471.9,6445.5
1,2025-10-27 01:00:00+08:00,6486.341388,6348.4,6316.9
2,2025-10-27 01:30:00+08:00,6385.410645,6243,6211.2
3,2025-10-27 02:00:00+08:00,6321.837062,6182.3,6127.5
4,2025-10-27 02:30:00+08:00,6258.047356,6116.6,6064.1
5,2025-10-27 03:00:00+08:00,6205.892086,6066.4,6017.1
6,2025-10-27 03:30:00+08:00,6176.630854,6036.3,5957.8
7,2025-10-27 04:00:00+08:00,6126.59312,5984.4,5932.7
8,2025-10-27 04:30:00+08:00,6034.924178,5892.5,5944.9
9,2025-10-27 05:00:00+08:00,5969.453389,5827.5,5941.7
10,2025-10-27 05:30:00+08:00,6018.491017,5875.6,5942.5
11,2025-10-27 06:00:00+08:00,6122.138131,5978.7,6013.8
12,2025-10-27 06:30:00+08:00,6347.675652,6202.5,6223.5
13,2025-10-27 07:00:00+08:00,6538.82055,6397,6380.7
14,2025-10-27 07:30:00+08:00,6789.251501,6643.5,6576.8
15,2025-10-27 08:00:00+08:00,6988.229357,6845,6784.6
16,2025-10-27 08:30:00+08:00,7258.967286,7114.8,7065.6
17,2025-10-27 09:00:00+08:00,7384.178009,7241.9,7213.9
18,2025-10-27 09:30:00+08:00,7505.011678,7364.2,7362.1
19,2025-10-27 10:00:00+08:00,7578.096433,7440.3,7395.8
20,2025-10-27 10:30:00+08:00,7705.555767,7561.2,7441.2
21,2025-10-27 11:00:00+08:00,7753.904425,7615.9,7470.7
22,2025-10-27 11:30:00+08:00,7732.985602,7588.1,7566.1
23,2025-10-27 12:00:00+08:00,7652.436392,7509.7,7572.4
24,2025-10-27 12:30:00+08:00,7561.627489,7417.7,7493.4
25,2025-10-27 13:00:00+08:00,7554.860455,7416.3,7435.9
26,2025-10-27 13:30:00+08:00,7605.358029,7462.9,7441.3
27,2025-10-27 14:00:00+08:00,7604.291081,7460.7,7478
28,2025-10-27 14:30:00+08:00,7585.198403,7443.4,7498.9
29,2025-10-27 15:00:00+08:00,7556.922177,7414.8,7490.6
30,2025-10-27 15:30:00+08:00,7542.956696,7400.4,7467.7
31,2025-10-27 16:00:00+08:00,7531.594738,7387.8,7448.1
32,2025-10-27 16:30:00+08:00,7579.021808,7436.2,7452.7
33,2025-10-27 17:00:00+08:00,7613.979537,7469.6,7456.6
34,2025-10-27 17:30:00+08:00,7647.695965,7502.6,7457.1
35,2025-10-27 18:00:00+08:00,7604.794085,7459.3,7441
36,2025-10-27 18:30:00+08:00,7519.38438,7377.8,7400.2
37,2025-10-27 19:00:00+08:00,7534.444803,7394.2,7419.8
38,2025-10-27 19:30:00+08:00,7501.667535,7363.2,7391.4
39,2025-10-27 20:00:00+08:00,7484.26365,7342.4,7369.4
40,2025-10-27 20:30:00+08:00,7465.265841,7323.4,7343.4
41,2025-10-27 21:00:00+08:00,7439.872308,7296.6,7304
42,2025-10-27 21:30:00+08:00,7373.080408,7233,7236.9
43,2025-10-27 22:00:00+08:00,7272.792728,7128.5,7124.2
44,2025-10-27 22:30:00+08:00,7100.038126,6959.6,6954.8
45,2025-10-27 23:00:00+08:00,6955.915777,6810.5,6804.4
46,2025-10-27 23:30:00+08:00,6800.740813,6657,6653
47,2025-10-28 00:00:00+08:00,6674.163511,6532.4,6524.6

In [27]:
assert len(monday) == 48
assert monday["Timestamp"].is_unique
assert monday["Timestamp"].is_monotonic_increasing

In [44]:
columns = raw.iloc[4, 1:4].tolist()

values = raw.iloc[5:53, 1:22].to_numpy()

# 48 × 7 × 3
# → 7 × 48 × 3
# → 336 × 3
values = (
    values
    .reshape(48, 7, 3)
    .transpose(1, 0, 2)
    .reshape(336, 3)
)


dates = pd.DatetimeIndex(
    pd.to_datetime(raw.iloc[1, 1:22:3])
)

expected_dates = pd.date_range(
    start=dates[0],
    periods=7,
    freq="D",
)

if not dates.equals(expected_dates):
    raise ValueError("Unexpected dates in EMA weekly file")

timestamps = pd.date_range(
    start=dates[0] + pd.Timedelta(minutes=30),
    periods=336,
    freq="30min",
    tz="Asia/Singapore",
)

week = pd.DataFrame(values, columns=columns)
week.insert(0, "Timestamp", timestamps)



week

,Timestamp,System Demand (Actual),NEM Demand (Actual),NEM Demand (Forecast)
0,2025-10-27 00:30:00+08:00,6613.229622,6471.9,6445.5
1,2025-10-27 01:00:00+08:00,6486.341388,6348.4,6316.9
2,2025-10-27 01:30:00+08:00,6385.410645,6243,6211.2
3,2025-10-27 02:00:00+08:00,6321.837062,6182.3,6127.5
4,2025-10-27 02:30:00+08:00,6258.047356,6116.6,6064.1
...,...,...,...,...
331,2025-11-02 22:00:00+08:00,7289.454108,7150.9,7115.5
332,2025-11-02 22:30:00+08:00,7159.45715,7023.2,7033.6
333,2025-11-02 23:00:00+08:00,7044.731401,6905.8,6931.8
334,2025-11-02 23:30:00+08:00,6916.952743,6778.2,6781.4
335,2025-11-03 00:00:00+08:00,6802.122052,6662.7,6719.1

In [43]:
assert len(week) == 336
assert week["Timestamp"].is_unique
assert week["Timestamp"].is_monotonic_increasing